### ISSUE TITLE
Theme Pages Content

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/health-commission#23]
Create the "Themes" content in `_themes`.

- [x] Add themes to `frasco.config.js` under `jekyll`
- [x] Add to `config.yml`

Front Matter:
- [x] Title (full name)
- [x] Short Title
- [x] Image
- [x] In-Depth Overview (should be a selectable list of posts)
- [x] Featured Post (should be a selectable list of posts with this theme assigned)
- [x] Description (post body)

**Comment by aleesteele** [comment]
1. This might seem obvious, but should I create a local `_themes` folder? I saw that Trade Guys didn't have one, and that there might be [support for a local folder](https://github.com/jekyll/jekyll/issues/6199), but I'm not sure what you mean by 'Create the 'themes' content in themes', because otherwise, don't themes default to minima or are a combination of layouts/includes/sass? Does this mean you want to give options for multiple layouts? Also, any particular name when added to the `_config.yml` file?

2. Front matter was added to Forestry.io.
